### ISSUE TITLE
Sticky in-manual navs

### ISSUE THREAD

**Issue by davidmcguiredesign** [php/web-php#1197]
Seeing a page’s position within the manual is useful even when halfway down a long page. 

Using a style injection extension, I added some simple CSS to make the breadcrumb nav and (because I don’t know its real name) the sibling-chapter nav sticky. The styles have worked so well for me that I think others might benefit from them becoming a standard part of the PHP site.

```css
#layout .layout-menu {
    position: sticky;
    top: 3rem; 
    max-height: calc(100vh - 3rem);
    overflow: auto;
}

#breadcrumbs {
    position: sticky;
    top: 0px;
    background: var(--dark-grey-color);
    z-index: 1;
}

@media (min-width: 768px) {
    #layout-content {
        border-top-left-radius: 1rem; /* [1] */
    }
}
```

<sup>\[1]</sup> The rounded corner subliminally signals that one has reached the top of the page. The radius also matches the new search modal.
