### ISSUE TITLE
<br> not working??

### ISSUE THREAD

**Issue by ProtocolLive** [php/web-php#741]
https://github.com/php/web-php/blob/462e7d1223a7fc7c6d0b322d09648be03ea4b793/releases/8.2/languages/pt_BR.php#L7
This line has a tag &lt;br>, but on the mobile page, the letters run out of space between them

![photo_2022-12-14_10-24-26](https://user-images.githubusercontent.com/39626142/207607171-abca250b-0711-4091-91bd-bda533fca691.jpg)

Android 12
OUI 4.1
Browser Edge 107

**Comment by cmb69** [comment]
Not really releated to mobile devices. The `<br>` element has `class=display-none-md` and there is the following rule:
````css
@media (max-width: 1000px)
.display-none-md {
    display: none;
}
````
So the `<br>` is not displayed. I don't know what's the reasoning behind that decision.
