### ISSUE TITLE
add night  mood

### ISSUE THREAD

**Issue by sajjadef98** [php/web-php#771]
add night mood to php.net like 
https://laravel.com/docs/10.x/readme
10music.ir 
Manbaenab.ir 
and...

**Comment by monicfenga** [comment]
try this custom css:

```css
:root {
    --background-color: #111;
    --background-text-color: #888;
    --content-text-color: #ddd;
    --content-background-color: var(--dark-grey-color);
    --dark-grey-color: #333;
    --dark-blue-color: #272d49;
    --medium-blue-color: #3b446d;
    --light-blue-color: #bdc2db;
    --dark-magenta-color: #CF82B1;
    --medium-magenta-color: #AE508D;
    --light-magenta-color: #AE508D;
}

#layout-content a:link, #layout-content a:visited {
    color: #7A86B8;
}

.refsect1 blockquote.note {
    color:var(--dark-grey-color)
}

.docs .classsynopsis, .refsect1 .fieldsynopsis, .refsect1 .dc-description, .docs .sect1 .dc-description,.refsect1 blockquote.note,
#usernotes .note .text, .example-contents > [class$="code"], .example-contents.screen, .informalexample .literallayout,.refsect1 .example-contents > [class$="code"], .refsect1 .example-contents.screen {
    filter:invert(1);
}
/* search results */
.tt-dropdown-menu {
    background: none repeat scroll 0 0 var(--dark-blue-color);
    border-bottom: 1px solid var(--medium-blue-color);
    box-shadow: 1px 0 1px -1px var(--medium-blue-color) inset, -1px 0 1px -1px var(--medium-blue-color) inset, 0 0 1px var(--dark-blue-color);
    color: var(--dark-grey-color);
}

.tt-dropdown-menu .result-heading {
    background-color: var(--dark-blue-color);
}

.tt-suggestion {
    background: var(--background-color);
    color:var(--background-text-color);
}

.tt-suggestion h4{
    color:var(--content-text-color);
}

.tt-dropdown-menu .search {
    color:var(--content-text-color);
    background: var(--medium-blue-color);
    text-shadow:none
}
```

(you can use Stylish or Styler browser plugin to add custom css to the page)

![demo](https://github.com/php/web-php/assets/39868412/503f87db-e898-4edf-839f-b128619b0f6e)
